name: Deploy Do An Application
run-name: ${{ github.actor }} is deploy final project
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd do_an_application
            git pull origin main
            sudo php artisan serve --host=ec2-54-151-251-240.ap-southeast-1.compute.amazonaws.com --port=80
